# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kvstore_pb2 as kvstore__pb2


class KeyValueStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/kvstore.KeyValueStore/Get',
        request_serializer=kvstore__pb2.GetRequest.SerializeToString,
        response_deserializer=kvstore__pb2.GetResponse.FromString,
        )
    self.Put = channel.unary_unary(
        '/kvstore.KeyValueStore/Put',
        request_serializer=kvstore__pb2.PutRequest.SerializeToString,
        response_deserializer=kvstore__pb2.PutResponse.FromString,
        )
    self.registerClient = channel.unary_unary(
        '/kvstore.KeyValueStore/registerClient',
        request_serializer=kvstore__pb2.RegisterRequest.SerializeToString,
        response_deserializer=kvstore__pb2.RegisterResponse.FromString,
        )
    self.clientRequest = channel.unary_unary(
        '/kvstore.KeyValueStore/clientRequest',
        request_serializer=kvstore__pb2.ClientRequest.SerializeToString,
        response_deserializer=kvstore__pb2.ClientRequestResponse.FromString,
        )
    self.clientQuery = channel.unary_unary(
        '/kvstore.KeyValueStore/clientQuery',
        request_serializer=kvstore__pb2.ClientQuery.SerializeToString,
        response_deserializer=kvstore__pb2.ClientQueryResponse.FromString,
        )
    self.appendEntries = channel.unary_unary(
        '/kvstore.KeyValueStore/appendEntries',
        request_serializer=kvstore__pb2.AppendRequest.SerializeToString,
        response_deserializer=kvstore__pb2.AppendResponse.FromString,
        )
    self.requestVote = channel.unary_unary(
        '/kvstore.KeyValueStore/requestVote',
        request_serializer=kvstore__pb2.VoteRequest.SerializeToString,
        response_deserializer=kvstore__pb2.VoteResponse.FromString,
        )
    self.updateConfigs = channel.unary_unary(
        '/kvstore.KeyValueStore/updateConfigs',
        request_serializer=kvstore__pb2.UpdateConfigsRequest.SerializeToString,
        response_deserializer=kvstore__pb2.UpdateConfigsResponse.FromString,
        )


class KeyValueStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    """ClientQuery RPC
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    """ClientRequest RPC
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def registerClient(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def clientRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def clientQuery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def appendEntries(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def requestVote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateConfigs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=kvstore__pb2.GetRequest.FromString,
          response_serializer=kvstore__pb2.GetResponse.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=kvstore__pb2.PutRequest.FromString,
          response_serializer=kvstore__pb2.PutResponse.SerializeToString,
      ),
      'registerClient': grpc.unary_unary_rpc_method_handler(
          servicer.registerClient,
          request_deserializer=kvstore__pb2.RegisterRequest.FromString,
          response_serializer=kvstore__pb2.RegisterResponse.SerializeToString,
      ),
      'clientRequest': grpc.unary_unary_rpc_method_handler(
          servicer.clientRequest,
          request_deserializer=kvstore__pb2.ClientRequest.FromString,
          response_serializer=kvstore__pb2.ClientRequestResponse.SerializeToString,
      ),
      'clientQuery': grpc.unary_unary_rpc_method_handler(
          servicer.clientQuery,
          request_deserializer=kvstore__pb2.ClientQuery.FromString,
          response_serializer=kvstore__pb2.ClientQueryResponse.SerializeToString,
      ),
      'appendEntries': grpc.unary_unary_rpc_method_handler(
          servicer.appendEntries,
          request_deserializer=kvstore__pb2.AppendRequest.FromString,
          response_serializer=kvstore__pb2.AppendResponse.SerializeToString,
      ),
      'requestVote': grpc.unary_unary_rpc_method_handler(
          servicer.requestVote,
          request_deserializer=kvstore__pb2.VoteRequest.FromString,
          response_serializer=kvstore__pb2.VoteResponse.SerializeToString,
      ),
      'updateConfigs': grpc.unary_unary_rpc_method_handler(
          servicer.updateConfigs,
          request_deserializer=kvstore__pb2.UpdateConfigsRequest.FromString,
          response_serializer=kvstore__pb2.UpdateConfigsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kvstore.KeyValueStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
